version: '3.4'

services:
  vpn:
    build:
      context: .
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    # read_only: true
    tmpfs:
      - /run
      - /tmp
    # restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    #ports:
      #- "8888:8888"
    env_file:
      - .env
    volumes:
      - /dev/net:/dev/net:z
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
      - ./vpn:/vpn
